# The following patch adds a directive for certmanager to inject CA into the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: "ignored" # not important, we are applying this patch to all CRDs
  annotations:
    cert-manager.io/inject-ca-from: giantswarm/cluster-api-core-cert
