resources:
  - bases/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
  - bases/addons.cluster.x-k8s.io_clusterresourcesets.yaml
  - bases/cluster.x-k8s.io_clusters.yaml
  - bases/cluster.x-k8s.io_machinedeployments.yaml
  - bases/cluster.x-k8s.io_machinehealthchecks.yaml
  - bases/cluster.x-k8s.io_machinesets.yaml
  - bases/cluster.x-k8s.io_machines.yaml
  - bases/exp.cluster.x-k8s.io_machinepools.yaml
patches:
  - path: patches/cainjection.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
  - path: patches/webhook.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
  - path: patches/versions/v1alpha3/addons.cluster.x-k8s.io_clusterresourcesetbindings.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: clusterresourcesetbindings.addons.cluster.x-k8s.io
  - path: patches/versions/v1alpha3/addons.cluster.x-k8s.io_clusterresourcesets.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: clusterresourcesets.addons.cluster.x-k8s.io
  - path: patches/versions/v1alpha2/cluster.x-k8s.io_clusters.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: clusters.cluster.x-k8s.io
  - path: patches/versions/v1alpha3/cluster.x-k8s.io_clusters.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: clusters.cluster.x-k8s.io
  - path: patches/versions/v1alpha2/cluster.x-k8s.io_machinedeployments.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: machinedeployments.cluster.x-k8s.io
  - path: patches/versions/v1alpha3/cluster.x-k8s.io_machinedeployments.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: machinedeployments.cluster.x-k8s.io
  - path: patches/versions/v1alpha3/cluster.x-k8s.io_machinehealthchecks.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: machinehealthchecks.cluster.x-k8s.io
  - path: patches/versions/v1alpha2/cluster.x-k8s.io_machinesets.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: machinesets.cluster.x-k8s.io
  - path: patches/versions/v1alpha3/cluster.x-k8s.io_machinesets.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: machinesets.cluster.x-k8s.io
  - path: patches/versions/v1alpha2/cluster.x-k8s.io_machines.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: machines.cluster.x-k8s.io
  - path: patches/versions/v1alpha3/cluster.x-k8s.io_machines.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: machines.cluster.x-k8s.io
  - path: patches/versions/v1alpha3/exp.cluster.x-k8s.io_machinepools.yaml
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: machinepools.exp.cluster.x-k8s.io
